version: "3.3"
services:
   webapp:
      image: python:3-alpine
      container_name: "webapp.${HOST}"
      env_file:
         - ./.env
      environment:
         - ALLOWED_HOSTS=192.168.14.3,192.168.14.3:5000
      volumes:
         - ./src:/usr/src/app:rw
         - logs:/usrc/app/logs:rw
      ports:
         - ${PORT}:${PORT}
      working_dir: /usr/src/app
      command: /usr/src/app/start run
volumes:
    logs: {}
